server:
  port: 8888

spring:
  application:
    name: "config-server"

  cloud:
    config:
      server:
        git:
          uri: "https://git-codecommit.ap-northeast-2.amazonaws.com/v1/repos/twd-config-repository"

